Fix EZP-27254: Command to clean up relations causing "Unknown relation type 0." exception
ezsystems/ezpublish-kernel pull request #1979
Opened 2017-05-09 10:01 UTC by adamwojs

> JIRA: https://jira.ez.no/browse/EZP-27254

# Description

This PR adds a console command to `EzPublishMigrationBundle` that clean up relations with invalid relation type (equal zero). Those relations are created by bug in legacy in specific conditions and cause "Unknown relation type 0." exception when the content object is accessed via REST API. More details: https://github.com/ezsystems/ezpublish-legacy/pull/1295. 

# Usage

The command can be executed in two modes:

* `fix` - Executes clean up 
*  `list` / `dry-run`  - Prints table with all corrupted relations that will be deleted:

```
Following relations will be removed:
ID      FCO_ID  FCO_V   TCO_ID  RT
4001    1840    3       8577    0
4002    3102    6       6061    0
...
4027    3649    6       6784    0 
```

# Clean Up

Internally invalid relations as deleted by the following SQL statement: 

```
DELETE FROM ezcontentobject_link WHERE relation_type = 0
```

2017-05-09 10:16 UTC, andrerom commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +        $connection = $this->getContainer()->get('ezpublish.connection');
Ideally should use doctrine connection, but as this is specific to legacy storage I guess it's ok.

2017-05-09 10:16 UTC, andrerom approved these changes
ping @bdunogier / @glye

2017-05-10 13:59 UTC, glye approved these changes
Aside from grammar nazi nitpicks, should be ok.

Should the script clear/invalidate related caches, or inform the user about that?

2017-05-10 13:59 UTC, glye commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +The command <info>%command.name%</info> clean up corrupted relations in Legacy Storage database. See: https://jira.ez.no/browse/EZP-27254
clean**s** up

2017-05-10 13:59 UTC, glye commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +exhaustion run it in production environment using <info>--env=prod</info> switch.
using **the**

2017-05-10 13:59 UTC, glye commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +        $output->writeln('Following relations will be removed: ');
**The f**ollowing

2017-05-11 07:54 UTC, adamwojs commented
PR updated with correction of the grammatical errors. Definitely grammar of natural languages is not my strong point

2017-05-11 08:53 UTC, bdunogier requested changes

2017-05-11 08:53 UTC, bdunogier commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +        $output->writeln("ID\tFCO_ID\tFCO_V\tTCO_ID\tRT");
Would it make more sense to use the Symfony's [Table](http://symfony.com/doc/2.7/components/console/helpers/table.html) ? While at it, I'd use slightly more informative header names.

2017-05-11 08:53 UTC, bdunogier commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +        $connection = $this->getContainer()->get('ezpublish.connection');
Is it ? We don't check anywhere if the legacy storage engine is used. We don't have another one at the moment, but it will fail in some future.

2017-05-11 14:05 UTC, andrerom commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +        $connection = $this->getContainer()->get('ezpublish.connection');
At that point this will have to be extracted into the engine right?

2017-05-12 07:47 UTC, adamwojs commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +        $output->writeln("ID\tFCO_ID\tFCO_V\tTCO_ID\tRT");
If all of those data into memory at once is not a problem, we can use them.

2017-05-12 13:24 UTC, bdunogier commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +        $output->writeln("ID\tFCO_ID\tFCO_V\tTCO_ID\tRT");
That is a good question. Could you measure how much is used by 1 item in there, so that we know how high the limit would be ?

2017-05-15 08:52 UTC, adamwojs commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +        $output->writeln("ID\tFCO_ID\tFCO_V\tTCO_ID\tRT");
I've got ~580b per row, calculating as the difference between `memory_get_usage()` invoked before and after loading 10^6 rows.

2017-05-17 20:55 UTC, bdunogier commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +        $output->writeln("ID\tFCO_ID\tFCO_V\tTCO_ID\tRT");
2000 relations per megabyte, then. 2 million with a gigabyte. What do you think @andrerom ? Worth it ?
Can you run it several times, @adamwojs ?

2017-05-18 13:21 UTC, andrerom commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +        $output->writeln("ID\tFCO_ID\tFCO_V\tTCO_ID\tRT");
Sounds safe enough, this is only listing those being removed, so I wouldn't expect that many of them. Or @adamwojs ?

2017-05-22 19:49 UTC, adamwojs commented
PR updated according to suggestions.

2017-05-22 20:44 UTC, adamwojs commented on eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/CleanUpRelationTypeEqZeroCommand.php
> +        $output->writeln("ID\tFCO_ID\tFCO_V\tTCO_ID\tRT");
It's hard to say, but I think it sounds reasonable for most installations. Of course, I assume that `list`/`dry-run` action it's only for preview purposes and for safety reasons before executing `fix` action, working backup is **required**.

2017-06-19 18:30 UTC, merged