Proposed changes to simplify custom Field Type creation
ezsystems/ezpublish-kernel pull request #2049
Opened 2017-07-12 07:30 UTC by kore

Proposed changes to simplify custom Field Type creation

2017-07-17 09:57 UTC, alongosz requested changes
Looks good, I found some minor issues:

2017-07-17 09:57 UTC, alongosz commented on doc/specifications/proposed/field_type.md
> +[tutorial](https://doc.ez.no/display/EZP/eZ+Publish+5+Field+Type+Tutorial).
If we omit optional methods, there will be no easy reference on how to implement them. Maybe we should create at least one "advanced" implementation that shows optional methods?

Side note: current version of FT tutorial is [here](https://github.com/ezsystems/TweetFieldTypeBundle/blob/documentation/docs/index.md)

2017-07-17 09:57 UTC, alongosz commented on doc/specifications/proposed/field_type.md
> +them to debug all those common subtile issues (naming, …).
Typo: subtle (?)

2017-07-17 09:57 UTC, alongosz commented on doc/specifications/proposed/field_type.md
> +`eZ\Publish\Core\FieldType\Tests\FieldTypeTest` which allows to test
The problem with `Core` namespace is that we tend to change its "contents" without a notice. If we intend for developers to extend it, maybe we should move it to `SPI`?

2017-07-17 09:57 UTC, alongosz commented on doc/specifications/proposed/field_type.md
> +But since the schema management inside eZ Publish is yet to be defined
`eZ Platform`, right? :)

2017-07-17 09:57 UTC, alongosz commented on doc/specifications/proposed/field_type.md
> +test explicitely testing that the returned handler is correct and
Typo: explicitly

2017-07-17 09:57 UTC, alongosz commented on doc/specifications/proposed/field_type.md
> +`eZ\Publish\Core\FieldType\FieldType` class. Omit all optional methods
We should rather encourage implementing `eZ\Publish\SPI\FieldType\FieldType` as there is a BC promise on SPI.

2020-05-28 12:52 UTC, closed without merging

2020-06-02 13:44 UTC, andrerom commented
@alongosz Anything here we should consider to apply to 3.x or 4.x?
Asking as engineering would need to drive this if something here is still relevant.

2020-06-02 13:49 UTC, alongosz commented
@andrerom I think this was approached differently and resolved via #2632.