[WIP] EZP-29916: As a developer, I want to validate passwords against blacklist
ezsystems/ezpublish-kernel pull request #2505
Opened 2018-12-17 21:42 UTC by adamwojs

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-29916](https://jira.ez.no/browse/EZP-29916)
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** | `7.5` 
| **BC breaks**      | no
| **Tests pass**     | ?
| **Doc needed**     | no

Follow up for the https://github.com/ezsystems/ezpublish-kernel/pull/2482 adds into the product an password validation against blacklist. 

**TODO**:
- [ ] Implement feature / fix a bug.
- [ ] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2019-01-11 08:48 UTC, pawbuj commented on eZ/Bundle/EzPublishCoreBundle/Command/ImportPasswordBlacklistCommand.php
> +        $passwords = array_map('trim', $passwords);
I would recommend hide those operations in loadPasswordsFile function and rename it to loadPasswords

2019-01-11 08:48 UTC, pawbuj commented on eZ/Publish/Core/Persistence/Legacy/Handler.php
>      public function contentHandler()
Please, add typehint of return valeu and docBlock.

2019-01-11 08:48 UTC, pawbuj commented on eZ/Publish/Core/Repository/UserService.php
> +    public function setLogger(LoggerInterface $logger = null)
Please add a docBlock and typyhint of return value.

2019-01-11 08:48 UTC, pawbuj commented on eZ/Publish/SPI/Persistence/Handler.php
> +    public function passwordBlacklistHandler();
typehint a return value

2020-04-17 11:38 UTC, alongosz requested changes
I like the idea in general. I'm sorry I haven't had time to review it back in the days.

Questions for v3 reality:
1. Shouldn't this be a responsibility of eZ Platform User Bundle now?
2. Is it really necessary to clutter schema with static data and persistence cache with a copy of it? Wouldn't it be better to use just a configuration file? What are pros of relying on database?

Remark: `ezplatform:password` feels strange, rather `ezplatform:user:password:...`

2020-05-28 12:52 UTC, closed without merging