Remove kriswallsmith/buzz from composer.json
ezsystems/ezpublish-kernel pull request #2717
Opened 2019-07-30 17:35 UTC by MarioBlazek

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | N/A
| **Bug/Improvement**| yes
| **New feature**    | yes
| **Target version** | `master` for features
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

`kriswallsmith/buzz` is not needed anymore in the kernel as REST has been moved to separate package.

2019-07-31 08:35 UTC, andrerom commented
Kind of duplicates https://github.com/ezsystems/ezpublish-kernel/pull/2596

2020-04-17 11:49 UTC, emodric commented
Hi! Will this ever be removed from 7.5.x branch? This old version of Buzz prevents usage of newer `psr/http-client` on which many HTTP based packages depend.

2020-04-17 11:58 UTC, andrerom commented
Well it needs to pass.

pinging @alongosz here due to his comment on meta repo: https://github.com/ezsystems/ezpublish-kernel/pull/2596#issuecomment-513779051

2020-04-17 12:17 UTC, alongosz requested changes
>> Hi! Will this ever be removed from 7.5.x branch? This old version of Buzz prevents usage of newer `psr/http-client` on which many HTTP based packages depend.
>
> Well it will need to pass tests.
> 
> pinging @alongosz here due to his comment on meta repo: [#2596 (comment)](https://github.com/ezsystems/ezpublish-kernel/pull/2596#issuecomment-513779051)

This needs to be rebased to `7.5` so we can see the current state of tests. AFAIR [#2596 (comment)](https://github.com/ezsystems/ezpublish-kernel/pull/2596#issuecomment-513779051) still applies.

Keep in mind that BehatBundle has a hard requirement on this package, so you'd need to drop it from your project(s). But as long as you don't need it it should be fine.

I expect we need to:
1. Rework REST tests execution to execute them from the package, not meta (needs to be fixed anyway at some point)
2. See what needs to be done to make Core Behat REST tests pass w/o it.

It will require a significant amount of time of a Sprint. As long as @SylvainGuittard or @lserwatka would allow, I could tackle those issues.

2020-04-17 12:23 UTC, andrerom commented
> Keep in mind that BehatBundle has a hard requirement on this package, so you'd need to drop it from your project(s). But as long as you don't need it it should be fine.

Long time since I looked deep into BehatBundle, but doesn't it support different backends as http clients? (old guzzle version and buzz)

Would it be worth it to make one using Symfony HttpClient to get rid of the old buzz/guzzle stuff?

Besides requiring PHP 7.1.3+ it seems to be pretty flexible on requirements: https://github.com/symfony/http-client/blob/4.4/composer.json

2020-04-17 12:28 UTC, alongosz commented
> > Keep in mind that BehatBundle has a hard requirement on this package, so you'd need to drop it from your project(s). But as long as you don't need it it should be fine.
> 
> Long time since I looked deep into BehatBundle, but doesn't it support different backends as http clients? (old guzzle version and buzz)
> 

I think that was the intention, but probably too outdated to support it out of the box. Need to try.

> Would it be worth it to make one using Symfony HttpClient to get rid of the old buzz/guzzle stuff?

For sure :)

2020-04-17 12:30 UTC, gggeek commented
Maybe I'm jumping the gun, but if "BehatBundle has a hard requirement on this package", would it not be enough to push the requirement into BehatBundle's composer.json ?

2020-04-17 12:31 UTC, gggeek commented
PS: I forgot the obligatory OT spam: what are the changes of ezsystems accepting a PR against the version of behatbundle which is used by ezp 5.4, to make it compatible with newer phpunit versions (and release a new tagged version)?

2020-04-17 12:45 UTC, alongosz commented
> Maybe I'm jumping the gun, but if "BehatBundle has a hard requirement on this package", would it not be enough to push the requirement into BehatBundle's composer.json ?

It's already there, therefore I've said that as long as it's not needed by a project, it can be dropped [from the project]. The issue at hand is that it's a requirement of Kernel as well and simple removal from composer.json is not enough.

> what are the changes of ezsystems accepting a PR against the version of behatbundle which is used by ezp 5.4

eZ Publish 5.4 is past EOM since November 2018. This means that the version of BehatBundle corresponding to eZ Publish 5.4 is also not supported. We accept major package upgrades on `master` versions, with some exceptions for specific cases (like security issue). Moreover if an upgrade would cause a BC break for 1st or 3rd party, it would be also rejected. However this is really code diff-based, so hard to tell.

2020-05-28 12:52 UTC, closed without merging