EZP-30978: fix issue when location limitation is used on content/edit policy
ezsystems/ezpublish-kernel pull request #2780
Opened 2019-09-26 15:57 UTC by florianalexandre

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-30978](https://jira.ez.no/browse/EZP-30978)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `7.x`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

https://jira.ez.no/browse/EZP-30978

**TODO**:
- [ ] Implement feature / fix a bug.
- [ ] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2019-09-27 09:51 UTC, mikadamczyk requested changes

2019-09-27 09:51 UTC, mikadamczyk commented on eZ/Publish/Core/Limitation/LocationLimitationType.php
> +            // As this is Role limitation we need to signal abstain on unsupported $object
Only SectionLimitation and SubtreeLimitation are available when you assign a Role to the User or User Group. I am not saying that we should not return `ACCESS_ABSTAIN` but not for this reason. Also, this change is not needed to solve this issue. I am in favor of not making this change now.

2019-09-27 09:51 UTC, mikadamczyk commented on eZ/Publish/Core/Limitation/LocationLimitationType.php
> +                // As this is Role limitation we need to signal abstain on unsupported $targets
The same here. LocationLimitation is not available when you assign a Role to the User or User Group. We get rid off `Versions` from `$targets`. I think that this change is not needed or at least explanation should be different.

2019-09-27 10:07 UTC, florianalexandre commented
I have gone a bit overboard after taking the subtree limitation as an exemple.
Reverted some modification to only keep what is need to fix the original issue.

2019-09-27 10:09 UTC, mikadamczyk approved these changes

2019-09-27 15:35 UTC, alongosz requested changes
Please add an integration test for the use case so we can all understand what is the setup which causes this issue. It can be created either in `\eZ\Publish\API\Repository\Tests\PermissionResolverTest` or in `\eZ\Publish\API\Repository\Tests\Values\User\Limitation\LocationLimitationTest`.

Moreover the solution needs to be changed so it applies to all Limitations (in a generic way), not just Location:

2019-09-27 15:35 UTC, alongosz commented on eZ/Publish/Core/Limitation/LocationLimitationType.php
> +            return !$target instanceof Version;
The actual bug exists in the implementation of `\eZ\Publish\Core\Repository\Permission\PermissionResolver::lookupLimitations`. 
An instance of `Target` should be passed to `TargetAwareType` Limitation type only, which [`canUser` takes into the account](https://github.com/ezsystems/ezpublish-kernel/blob/v7.5.4/eZ/Publish/Core/Repository/Permission/PermissionResolver.php#L224). The `lookupLimitation` method needs to behave the same way. // cc @mikadamczyk 

While this fix works for `LocationLimitation`, there might be similar issues 

Ref:
- `\eZ\Publish\SPI\Limitation\TargetAwareType`,
- `\eZ\Publish\SPI\Limitation\Target`.

2022-04-19 14:47 UTC, adamwojs commented
Closing PR as obsolete. eZ Platform 2.5 has reached EOM, so please reopen PR in ezsystems/ezplatform-kernel (bug fixes) or ibexa/core (features/improvements) if issue is still valid for v3.3 / v4.x and you are willing to work on it.

2022-04-19 14:47 UTC, closed without merging