[WIP]EZEE-3159 added support for items in the trash for SubtreeLimitationType and LocationLimitationType
ezsystems/ezpublish-kernel pull request #3040
Opened 2020-06-03 15:23 UTC by mateuszdebinski

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZEE-3159](https://jira.ez.no/browse/EZEE-3159)
| **Bug**| yes
| **New feature**    | no
| **Target version** | `7.5` 
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [ ] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2020-06-09 09:10 UTC, mikadamczyk commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
> +     * @param int $rootLocationId
```suggestion
     * @param int $rootLocationId|null
```

2020-06-09 09:10 UTC, mikadamczyk commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
> +    abstract public function loadLocationDataByTrashContent($contentId, $rootLocationId = null);
This is a new method and we can add type hint here

2020-06-10 06:49 UTC, ViniTou commented on eZ/Publish/SPI/Persistence/Content/Location/Handler.php
> +     * Loads all locations for $contentId in trash, optionally limited to a sub tree
Not a fan of this comment repeated 4 times.

2020-06-10 06:49 UTC, ViniTou commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Mapper.php
> +     * @param Location $location
FQCN

2020-06-10 06:51 UTC, ViniTou reviewed
Are we still waiting for unit/integration tests?

2020-06-10 06:51 UTC, ViniTou commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
> +    abstract public function loadLocationDataByTrashContent(int $contentId, int $rootLocationId = null): array;
typehint specific array in phpdoc

2020-06-18 10:14 UTC, mikadamczyk approved these changes

2020-06-18 10:14 UTC, mikadamczyk commented on eZ/Publish/Core/Persistence/Cache/LocationHandler.php
> +    public function loadLocationsByTrashContent(int $contentId, int $rootLocationId = null): array
```suggestion
    public function loadLocationsByTrashContent(int $contentId, ?int $rootLocationId = null): array
```

2020-06-18 10:14 UTC, mikadamczyk commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
> +    abstract public function loadLocationDataByTrashContent(int $contentId, int $rootLocationId = null): array;
```suggestion
    abstract public function loadLocationDataByTrashContent(int $contentId, ?int $rootLocationId = null): array;
```

2020-06-18 10:14 UTC, mikadamczyk commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
> +    public function loadLocationDataByTrashContent(int $contentId, int $rootLocationId = null): array
```suggestion
    public function loadLocationDataByTrashContent(int $contentId, ?int $rootLocationId = null): array
```

2020-06-18 10:14 UTC, mikadamczyk commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
> +    public function loadLocationDataByTrashContent(int $contentId, int $rootLocationId = null): array
```suggestion
    public function loadLocationDataByTrashContent(int $contentId, ?int $rootLocationId = null): array
```

2020-06-18 10:14 UTC, mikadamczyk commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
> +    public function loadLocationsByTrashContent(int $contentId, int $rootLocationId = null): array
```suggestion
    public function loadLocationsByTrashContent(int $contentId, ?int $rootLocationId = null): array
```

2020-06-18 10:14 UTC, mikadamczyk commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Mapper.php
> +    public function createLocationsFromRows(array $rows, $prefix = '', Location $location = null)
```suggestion
    public function createLocationsFromRows(array $rows, $prefix = '', ?Location $location = null)
```

2020-06-18 10:14 UTC, mikadamczyk commented on eZ/Publish/SPI/Persistence/Content/Location/Handler.php
> +    public function loadLocationsByTrashContent(int $contentId, int $rootLocationId = null): array;
```suggestion
    public function loadLocationsByTrashContent(int $contentId, ?int $rootLocationId = null): array;
```

2020-06-18 10:18 UTC, konradoboza approved these changes

2020-06-18 13:02 UTC, devmysz requested changes

2020-06-18 13:02 UTC, devmysz commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
> +    protected function applySubtreeLimitation(DatabaseQuery $query, $rootLocationId, string $tableName = 'ezcontentobject_tree')
Please split this line and add return type `void`

2020-06-18 13:02 UTC, devmysz commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Mapper.php
> +     * @param \eZ\Publish\SPI\Persistence\Content\Location $location
```suggestion
     * @param \eZ\Publish\SPI\Persistence\Content\Location|null $location
```

2020-06-18 13:02 UTC, devmysz commented on eZ/Publish/Core/Persistence/Legacy/Content/Location/Mapper.php
> +     * @param \eZ\Publish\SPI\Persistence\Content\Location $location
```suggestion
     * @param \eZ\Publish\SPI\Persistence\Content\Location|null $location
```

2020-06-18 13:02 UTC, devmysz commented on eZ/Publish/API/Repository/Tests/TrashServiceTest.php
> +        $query->filter = new Criterion\LogicalAnd(
This filter is unnecesary if you want to get all trash items

2020-06-18 13:22 UTC, devmysz approved these changes
👌

2020-06-18 13:22 UTC, adamwojs approved these changes

2020-06-19 12:54 UTC, katarzynazawada approved these changes

2020-06-19 13:12 UTC, merged

2020-06-22 09:13 UTC, lserwatka commented
@mateuszbieniek you can merge it up to ezplatform-kernel/1.0 and master.

2020-06-22 09:45 UTC, mateuszbieniek commented
@lserwatka I think you pinged wrong Mateusz ;) @mateuszdebinski

2020-06-22 11:32 UTC, mateuszdebinski commented
@lserwatka I did it in the morning