EZP-31677: Added normalizer to decrese amount of date when compound matcher is encoded to JSON
ezsystems/ezpublish-kernel pull request #3041
Opened 2020-06-04 08:41 UTC by mikadamczyk

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31677](https://jira.ez.no/browse/EZP-31677)
| **Bug** | yes
| **New feature**    | no
| **Target version** | `6.13`/
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2020-06-04 10:31 UTC, alongosz requested changes
+1
CS: please run up-to-date CS fixer check (ideally by merging up these changes into detached head of 7.5, since the rules are up to date there - wasn't possible to have eZ Platform Code Style on 6.13 due to Symfony version coupling).

2020-06-04 10:31 UTC, alongosz commented on eZ/Publish/Core/MVC/Symfony/Component/Serializer/CompoundMatcherNormalizer.php
> +namespace eZ\Publish\Core\MVC\Symfony\Component\Serializer;
Missing header

2020-06-04 10:31 UTC, alongosz commented on eZ/Publish/Core/MVC/Symfony/Component/Serializer/CompoundMatcherNormalizer.php
> +     */
CS: skip please

2020-06-04 10:31 UTC, alongosz commented on eZ/Publish/Core/MVC/Symfony/Component/Serializer/CompoundMatcherNormalizer.php
> +     */
CS

2020-06-04 10:34 UTC, adamwojs approved these changes
+1 besides nitpicks mentioned by @alongosz

2020-06-04 10:43 UTC, alongosz approved these changes

2020-06-04 11:20 UTC, ViniTou approved these changes

2020-06-08 13:56 UTC, micszo approved these changes
Retested on 1.13.5, 2.5.10 and 3.0. Problem does not occur anymore. Went through the list of machters and didn't find new issues.

2020-06-08 14:04 UTC, merged