EZP-31680: Provided `languageCode` param to REST Views
ezsystems/ezpublish-kernel pull request #3043
Opened 2020-06-09 14:54 UTC by barw4

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31680](https://jira.ez.no/browse/EZP-31680)
| **Bug/Improvement**| no
| **New feature**    | yes
| **Target version** | `7.5`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

REST will now utilize `languageCode` param in order to find `Content` in the chosen language.

**TODO**:
- [x] Implement feature.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2020-06-15 11:55 UTC, adamwojs commented
Just for the record: if the goal here is to align "standalone" and UDW search behaviour then we propably need more then just \`languageCode\` parameter. See  https://github.com/ezsystems/ezplatform-admin-ui/blob/master/src/bundle/Controller/SearchController.php#L158-L170 for more details. Please double check it // cc @michal-myszka

2020-06-15 13:11 UTC, barw4 commented
@adamwojs please, see here: https://github.com/ezsystems/ezpublish-kernel/pull/3043/commits/f8df7ca0be4e22ea49ef8bb7a81d67d32ffe78cd

2020-06-15 13:29 UTC, michal-myszka commented
If you want to have an "always_available" option and be align with "standalone" searching, your actual changes is right. If you wan't to add an "always_available" option, you need to pass only language code.

2020-06-18 10:11 UTC, Nattfarinn requested changes

2020-06-18 10:11 UTC, Nattfarinn commented on eZ/Publish/Core/REST/Server/Values/RestViewInput.php
> +     * @var bool
```suggestion
     * @var bool|null
```

2020-06-18 10:11 UTC, Nattfarinn commented on eZ/Publish/Core/REST/Server/Controller/Views.php
> +        if (!empty($viewInput->query->query->value)) {
`->query->query->value` is not very descriptive. Expose first level as a local variable or make a private checker method (`isSomething`/`hasSomething`) for a whole `if` condition.

2020-06-18 10:27 UTC, mikadamczyk approved these changes
besides comments above

2020-06-18 13:12 UTC, devmysz approved these changes

2020-06-18 13:16 UTC, adamwojs approved these changes
+1 but please remember to mirror this PR to https://github.com/ezsystems/ezplatform-rest and document endpoints changes in https://github.com/ezsystems/ezplatform-rest-reference

2020-06-19 13:16 UTC, merged