fix-EZP-31779
ezsystems/ezpublish-kernel pull request #3053
Opened 2020-07-29 14:02 UTC by lionelakpagni

Adding language filter parameter.
Forgotten here: https://github.com/ezsystems/ezpublish-kernel/commit/494b58835b3992ba8caf9b8300d44b98b1e76983

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31779](https://jira.ez.no/browse/EZP-31779)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `6.x`/`7.x` for bug fixes or improvements _(on existing features)_, `master` for features
| **BC breaks**      | yes/no
| **Tests pass**     | yes/no
| **Doc needed**     |no

**TODO**:
- [ ] Implement feature / fix a bug.
- [ ] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2020-07-29 14:32 UTC, andrerom approved these changes
+1, but you can use more expressive PR titles (and optionally commit messages), in this case maybe `EZP-31779: Add missing language filtering in LocationSearchHitAdapter->getNbResult() breaking paging`

_Also should add test coverage for this, but for that maybe someone in Engineering can give you some hints, or maybe some in Support can help you on it. You can find some hints in https://github.com/ezsystems/ezpublish-kernel/pull/2940, but it's huge so search for adapter to see what is relevant, and in your case you should look for test class for location hit adapter to adapt instead._

2020-07-30 07:11 UTC, adamwojs reviewed
+1 but as @andrerom  said we should add test coverage for this. 

In `\eZ\Publish\Core\Pagination\Tests\LocationSearchHitAdapterTest` we need to check if `\eZ\Publish\API\Repository\SearchService::findLocations` has been invoked with `$langaugeFilter`. Exaclly the same as it was done in  `\eZ\Publish\Core\Pagination\Tests\ContentSearchHitAdapterTest`.

2020-07-30 07:50 UTC, ViniTou commented
What is more, It also seams that those failing test on solr are related to this change:
https://travis-ci.org/github/ezsystems/ezpublish-kernel/jobs/712925198

it seems like the results are now in reversed order.
(not sure if somehow related to this, https://github.com/ezsystems/ezpublish-kernel/pull/3029, @alongosz )

2020-07-30 09:08 UTC, alongosz requested changes
> it seems like the results are now in reversed order.
> (not sure if somehow connected with this, #3029, @alongosz )

It uses stable 1.5.8, while it should use 1.5.x-dev. I'm not sure why. Branch tests are passing, so somehow this PR affects that, but it doesn't make sense. Anyway, w/o passing tests and w/o mentioned additional test coverage I can't accept the PR. I can look into Solr version requirement myself, but this will take some time.

2020-07-30 09:33 UTC, pspanja commented
> it seems like the results are now in reversed order.

Not reversed, but ordered lexicographically, so somehow connected to ID sort clause change. Probably the tests are not updated for this release.

2026-06-25 14:14 UTC, closed without merging