EZP-31110: Fix URLAlias utilizing `tree_root.location_id` option
ezsystems/ezpublish-kernel pull request #3065
Opened 2020-09-16 21:45 UTC by barw4

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31110](https://jira.ez.no/browse/EZP-31110)
| **Bug**| yes
| **New feature**    | no
| **Target version** | 7.5
| **BC breaks**      | ?
| **Tests pass**     | ?
| **Doc needed**     | no

Using `place at site root` option in case of using `tree_root.location_id` would never match any URLAlias because of `$pathPrefix` being included into search when `tree_root.location_id` is used.

**TODO**:
- [x] Implement feature / fix a bug.
- [ ] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2020-09-17 06:19 UTC, andrerom commented
Is this perhaps a misunderstanding of the feature?

Afaik "place at site root" is badly named, it really is about "place at content root" as repo _for the most_ part knows nothing about what a site is.

We should maybe check with what legacy did here, and if we want a site root feature then we either need to let user pick site it should be on to deduct path based on root location of that site.

Or in the case of virtual URL's like what you are proposing here, then we need to make it clear it will be available in all site**s**, even if content might not be available.

2020-09-17 07:50 UTC, barw4 commented
> Afaik "place at site root" is badly named, it really is about "place at content root" as repo _for the most_ part knows nothing about what a site is.

Isn't it how it behaves? Site root = content root if option `tree_root.location_id` is configured in a given SA. It's just the naming after option from the Custom URLAlias's form. This PR is not about URLAlias being SiteAccess aware, it only checks what is the content root for a given SA but it was already done like that before, I haven't changed this behavior.

> Or in the case of virtual URL's like what you are proposing here, then we need to make it clear it will be available in all sites, even if content might not be available.

Why would it be available? If the SA has such Content available due to .yml config param mentioned above it should match. If we have a Custom URL: `/foo/bar` with used "place at site root" option checked one would expect it will match the following URL:
`[SA]/foo/bar` where `tree/root` is the root location of SA we are accessing and the Content is located at `tree/root/foo/bar`.

2020-09-21 14:47 UTC, andrerom commented
TBH a bit unsure, but I can't remember legacy having to do two lookups to UrlAlias like this so might need a look by Engineering / PM on how this feature is intended to behave. /cc @SylvainGuittard

2020-09-28 10:13 UTC, alongosz requested changes, later dismissed
~As André mentioned, it requires PM input.~
~Either SylvainGuittard or bdunogier provide a specification for this feature please.~

2020-10-13 15:06 UTC, barw4 commented
Closed in favor of https://github.com/ezsystems/ezplatform-admin-ui/pull/1583

2020-10-13 15:06 UTC, closed without merging