EZP-32308: At least one valid Location is required in targets
ezsystems/ezpublish-kernel pull request #3083
Opened 2021-01-28 13:26 UTC by ViniTou

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-32308](https://jira.ez.no/browse/EZP-32308)
| **Bug/Improvement**| yes
| **New feature**    | no
| **Target version** | `7.5`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

Instead of requiring that all `targets` must be instance of `Location`, at least one valid is needed.

**TODO**:
- [ ] Implement feature / fix a bug.
- [ ] Implement tests.
- [ ] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2021-01-29 10:21 UTC, alongosz requested changes
1. It's a bit unclear to me what is present in $targets which causes the issue. Based on the description there should be no such issue, on the contrary - only Location should be present
1. This requires **integration** test coverage (we already have similar tests).
1. Commit message & PR title needs to be rephrased to follow the conventions.

2021-01-29 11:44 UTC, ViniTou commented
>It's a bit unclear to me what is present in $targets which causes the issue. Based on the description there should be no such issue, on the contrary - only Location should be present.

Only `\eZ\Publish\SPI\Limitation\Target\Version` was provided inside adminUI checks.

2021-02-02 08:07 UTC, Nattfarinn reviewed
I'm confused. Location limitation is probably one of the most used limitations in the system. How did it not explode earlier? Is it really the very first occurrence of mixed `$target`s (which could be pretty common actually)?

2021-02-02 13:27 UTC, ViniTou commented
@Nattfarinn 
>Is it really the very first occurrence of mixed $targets (which could be pretty common actually)?

No it is not, and all other places were systematically patched up and fixed (@mikadamczyk).
You may even see that same logic below in that same class
https://github.com/ezsystems/ezpublish-kernel/pull/3083/files#diff-a2d05e3e6c6fceef94a01e793d3e02b31b4d8d320f0535181fc5855c8db43f85R178

2021-02-03 08:13 UTC, mikadamczyk commented
I'm not sure if this limitation change should actually be removed. From what I can see in PR `EZP-30344: Allowed limiting Content management to specific translations (# 2585)` then when adding the method `prepareTargetsForType` to` PermissionResolver` https://github.com/ezsystems/ezpublish-kernel/pull/2585/files#diff-0f692381531f1f40b194e997c1e98f1c72bd6ca3f97de35274be3cfeca8d5e6fR424 was added https://github.com/ezsystems/ezpublish-kernel/pull/2585/files#diff-23d89diff-23d89diff-23d89diffed965cf6b531diff-23d89diffed965c

For me, if we allow the possibility that Limitation can get different targets, then it should not throw this exception. Because in every place (old and new) you will need to know/remember that before doing LimitationType::evaluate you have to filter the targets

2021-02-03 17:36 UTC, alongosz approved these changes

2021-02-12 11:29 UTC, tomaszszopinski approved these changes
QA approved on eZPlatform 2.5 & v2.5.16 with patch & diff.

2021-02-12 20:36 UTC, merged

2021-02-12 20:37 UTC, adamwojs commented
Could you please merge up changes @ViniTou?