EZP-32401: Added trashed Contents support to LocationLimitation
ezsystems/ezpublish-kernel pull request #3093
Opened 2021-03-25 09:54 UTC by barw4

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-32401](https://jira.ez.no/browse/EZP-32401)
| **Bug**| yes
| **New feature**    | no
| **Target version** | 7.5
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

When Content was trashed and it had reverse relation the Location was not accessible. Therefore additional condition had to be added which exports trashed Location and uses it as a target.

**TODO**:
- [x] Fix a bug.
- [ ] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2021-03-25 11:42 UTC, damianz5 approved these changes

2021-03-25 11:43 UTC, alongosz requested changes
The use case should be easily reproducible via integration test. 

_Besides commit message and PR title can be formed better (plural here is not "contents"). How about "Fixed handling trashed Content by LocationLimitation"?_

2021-03-25 13:58 UTC, barw4 commented
@alongosz integration test added in https://github.com/ezsystems/ezpublish-kernel/pull/3093/commits/54513acfb3f23da520b95390c039724a61f6b3fc

2021-03-25 14:03 UTC, alongosz approved these changes

2021-03-29 13:30 UTC, tomaszszopinski approved these changes
QA approved on eZPlatform 2.5 & v2.5.17 with patch & diff.

2021-03-29 13:32 UTC, merged

2021-03-29 13:32 UTC, lserwatka commented
Could you merge it up?

2021-03-29 13:43 UTC, barw4 commented
Holding on with merge until https://github.com/ezsystems/ezpublish-kernel/pull/3092 is merged.