[WIP] IBX-148: RemoveField allowed to delete orphaned Relations
ezsystems/ezpublish-kernel pull request #3099
Opened 2021-05-06 15:04 UTC by barw4

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [IBX-148](https://jira.ez.no/browse/IBX-148)
| **Bug**| yes
| **New feature**    | no
| **Target version** | `7.5`
| **BC breaks**      | no
| **Tests pass**     | [WIP]
| **Doc needed**     | no

Additional method has been added to `Content\Gateway` which deletes orphaned Relations resulting of an `ezobjectrelation` and `ezobjectrelationlist` fieldtypes deletion.

**TODO**:
- [x] Fix a bug.
- [ ] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [ ] Ask for Code Review.

2021-05-06 17:43 UTC, lserwatka commented on eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater/Action/RemoveField.php
> +            $this->fieldDefinition->fieldType === 'ezobjectrelationlist'
We should not hardcode this here, can we take it from some constant? FieldType perhaps?

2021-05-07 06:16 UTC, mikadamczyk commented on eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
> +    abstract public function removeRelationsViaFieldDefinitionId(int $fieldDefinitionId);
```suggestion
    abstract public function removeRelationsByFieldDefinitionId(int $fieldDefinitionId);
```

2021-05-07 06:19 UTC, mikadamczyk commented on eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater/Action/RemoveField.php
> +            || $this->fieldDefinition->fieldType === 'ezobjectrelationlist'
Why double-check the same?

2021-05-10 14:03 UTC, barw4 commented on eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater/Action/RemoveField.php
> +            $this->fieldDefinition->fieldType === 'ezobjectrelationlist'
I'm afraid we don't have those constants easily accessible anywhere besides a direct `public function` method used in the FieldType object. We are also directly referencing those values in different places (for example https://github.com/ezsystems/ezpublish-kernel/blob/7.5/eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php#L1518) so I thought that would be more 'natural' way to handle this.

2021-05-10 17:44 UTC, barw4 commented
The problem will still exist for older relations, should we create `db-update-x.sql` script or leave it like this?

2021-05-11 10:23 UTC, alongosz requested changes

2021-05-11 10:23 UTC, alongosz commented on eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
> +     * @see \eZ\Publish\API\Repository\ContentTypeService::removeFieldDefinition()
```suggestion
     * @covers \eZ\Publish\API\Repository\ContentTypeService::removeFieldDefinition
```

2021-05-11 10:23 UTC, alongosz commented on eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
> +     *
Redundant
```suggestion
```

2021-05-11 10:23 UTC, alongosz commented on eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
> +        $relationFieldCreate->isSearchable = false;
This block can be extracted to a separate method to improve readability.

2021-05-11 10:23 UTC, alongosz commented on eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
> +        $this->assertEquals(0, $relationsCount);
How about:
```suggestion
        self::assertCount(0, $contentService->loadRelations($content->versionInfo));
```

2021-05-11 10:23 UTC, alongosz commented on eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater/Action/RemoveField.php
> +            || $this->fieldDefinition->fieldType === 'ezobjectrelationlist'
well... moving those literals to some consts in Relation and RelationList Type classes wouldn't hurt. Here for readability you could refactor it as a private/local method: `isRelationFieldType(FieldDefinition $fieldDefinition): bool`

2021-05-13 06:35 UTC, webhdx approved these changes

2021-05-13 06:36 UTC, ViniTou approved these changes

2021-05-13 06:36 UTC, mikadamczyk approved these changes

2021-05-13 06:49 UTC, alongosz approved these changes

2021-05-13 07:13 UTC, Steveb-p approved these changes

2021-05-13 07:19 UTC, adamwojs requested changes

2021-05-13 07:19 UTC, adamwojs commented on eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater/Action/RemoveField.php
> +        }
This shouldn't be limited to `ezobjectrelation` and `ezobjectrelationlist` field types. Exacly the same issue will occurs for any field type exposing relations e.g image asset, richtext, page builder, custom field type.

2021-05-13 08:56 UTC, barw4 commented on eZ/Publish/Core/Persistence/Legacy/Content/Type/ContentUpdater/Action/RemoveField.php
> +        }
indeed, that is the case. https://github.com/ezsystems/ezpublish-kernel/pull/3099/commits/65ebf380f55e83a5fce1c0b2a048bee32cb76ad3 - I have skipped the check for the field being relation, running delete query each time the field is deleted wouldn't hurt I guess.

2021-05-13 10:35 UTC, damianz5 approved these changes

2021-05-13 10:51 UTC, adamwojs approved these changes

2021-05-14 10:59 UTC, micszo approved these changes
QA Approved on eZ Platform EE v2.5.19 with diff.

2021-05-17 05:29 UTC, merged

2021-05-17 05:30 UTC, adamwojs commented
@barw4 Could you please merge up changes?

2021-05-17 12:36 UTC, barw4 commented
Merged into:
 `1.2`: https://github.com/ezsystems/ezplatform-kernel/commit/6fb537e0c33e67671c5d1adf8125354b5b759e53
`1.3`: waiting for tests to pass