IBX-362: Fixed 'user/password' policy check
ezsystems/ezpublish-kernel pull request #3101
Opened 2021-05-11 14:45 UTC by barw4

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [IBX-362](https://jira.ez.no/browse/IBX-362)
| **Bug**| yes
| **New feature**    | no
| **Target version** | `7.5`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

Not sure why the `content/edit` policy was required when changing the password, this one has been removed.

Also, this issue is occurring because of Role limitations like the Subtree one. What is happening is that the "User" content is validated against the Subtree limitation (and it fails because of limitation on `Home` content for example) which shouldn't be the case for `user/*` policies as we don't deal with the usual content here. Therefore, the additional target has been added in order to abstain from evaluating this limitation as it doesn't make sense in the case of a user.

**TODO**:
- [x] Fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2021-05-11 15:29 UTC, gggeek commented
What about the opposite: can a content/edit policy be used to alter the password ?

2021-05-11 21:25 UTC, glye requested changes
I have my doubts that this is a bug at all, but I need more clarity in what the setup is. So: Assuming we have a role containing the user/password policy, assigned with subtree limitation on the Home folder.

Generally, a role assigned by subtree limitation applies when the content in question is located within the given subtree. Changing the password means making a change to the user. The user isn't in the Home subtree, so access is denied. This seems to make no sense for the user/password policy, at first glance.

However, what if I for whatever reason wanted to limit password changing to user group X? Then I might make a role with the user/password policy and assign it with subtree limitation to X. This would work as expected with the current code. After the fix, the role would work for all users, regardless of user group. That doesn't seem right.

Second, important concern: Will this change let people change the password of any other user, through the api? That would obviously be Very Bad™, and must be verified.

We can discuss whether it makes any sense to stop anyone from changing their own password, but as it stands, the role system does allow us to stop that, and I don't like to change that without very serious consideration by core devs. The requirement for content/edit is another thing, it does seem right to drop that, as the earlier fix indicates.

Now, if we take a step back and look at https://github.com/ezsystems/ezplatform-kernel/pull/117 - it says:
_Basically, to keep backward compatibility with previous kernel version, updateUser method is not really changed other than refactoring duplicate code. A new updateUserPassword is introduced that has the same arguments as updateUser._
Maybe the only fix we need is to make sure we use updateUserPassword rather than updateUser?

I would suggest some other changes:

- Doc: This should say that user/password must be assigned without limitation, or with a limitation matching the user in question. https://doc.ibexa.co/en/latest/guide/user_management/user_management/#changing-and-recovering-passwords
- Doc: This should not say that the user/password policy is "unused", when it clearly is in use. https://doc.ibexa.co/en/latest/guide/permissions/#available-policies
- Default data: All users should probably be allowed to change their own password by default, so we need a role with the user/password policy, assigned without limitations.

2021-05-12 06:30 UTC, mikadamczyk requested changes
Removing policy check will be a BC break. I face this issue in https://issues.ibexa.co/browse/EZP-28917 `To keep BC allow updating password if the user has content / edit policy.`. The other thing is we have the same check in `updateUserPassword` method. So, the bugfix should take care of an issue with the subtree limitation. Because some people could depend on this.

2021-05-12 15:13 UTC, barw4 commented
@glye 
>However, what if I for whatever reason wanted to limit password changing to user group X? Then I might make a role with the user/password policy and assign it with subtree limitation to X. This would work as expected with the current code. After the fix, the role would work for all users, regardless of user group. That doesn't seem right.

I can understand the need, but that should be the case for `user/password` policy as well. Please note that we are not allowed to put any limitations in the policy itself as there aren't any, whether, for other content-related policies, we do have Subtree limitations and others. That means that the `user/password` policy was not really prepared to handle any limitations. The user should be able to change his own password at any time if he has this policy. If we want to disable this option we should really remove such a policy from his role. 

>Second, important concern: Will this change let people change the password of any other user, through the api? That would obviously be Very Bad™, and must be verified.

As @mikadamczyk mentioned, I have brought back the {{content/edit}} policy check so that shouldn't occur.

To summarize, after https://github.com/ezsystems/ezpublish-kernel/pull/3101/commits/d44d926146fa0deca0ad67125e4a9c235f4cac5c the only change that I did was to add additional `targets` to limitations, so the only difference that is now present is that all Limitations are skipped for `user/password` policy (and that looks like it should be the case to the points I have raised above).

2021-05-13 06:42 UTC, mikadamczyk approved these changes

2021-05-13 06:49 UTC, ViniTou approved these changes

2021-05-13 06:52 UTC, alongosz approved these changes
This can be covered by integration tests most likely

2021-05-13 07:13 UTC, Steveb-p approved these changes

2021-05-13 07:57 UTC, adamwojs approved these changes

2021-05-13 12:24 UTC, barw4 commented
@alongosz test added in https://github.com/ezsystems/ezpublish-kernel/pull/3101/commits/a314c4dc6757e97103da868b9fe582444eb48383

2021-05-13 13:20 UTC, alongosz approved these changes

2021-05-14 07:25 UTC, glye approved these changes

2021-05-17 10:31 UTC, micszo approved these changes
QA Approved on eZ Platform EE v2.5.19 with diff.

2021-05-17 10:37 UTC, merged

2021-05-17 10:37 UTC, lserwatka commented
Could you merge it up?

2021-05-17 12:36 UTC, barw4 commented
Merged into:
 `1.2`: https://github.com/ezsystems/ezplatform-kernel/commit/6fb537e0c33e67671c5d1adf8125354b5b759e53
`1.3`: waiting for tests to pass