IBX-374: Fixed retrieving factory names in LazyDoctrineRepositoriesPass
ezsystems/ezpublish-kernel pull request #3103
Opened 2021-05-13 13:58 UTC by webhdx

| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [IBX-374](https://jira.ez.no/browse/IBX-374)
| **Bug**| yes
| **New feature**    | no
| **Target version** | `7.5` 
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

2021-05-13 14:00 UTC, Steveb-p approved these changes

2021-05-13 14:04 UTC, alongosz requested changes
LazyDoctrineRepositoriesPassTest looks like a good place to add coverage for this case, the solution looks ok.

2021-05-17 11:34 UTC, webhdx commented
@alongosz Added coverage for this case in existing test: 0f97074

2021-05-19 10:13 UTC, alongosz approved these changes

2021-05-25 07:05 UTC, bogusez approved these changes

2021-05-25 13:23 UTC, merged