IBX-1310: Created slots for assigning/unassigning user to groups
ezsystems/ezpublish-kernel pull request #3125
Opened 2021-10-22 15:54 UTC by barw4

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1310](https://issues.ibexa.co/browse/IBX-1310)
| **Type**                                   | bug
| **Target eZ Platform version** | `v2.5`
| **BC breaks**                          | no

The related Slots were missing for `assignUserToUserGroup` and `unAssignUserToUserGroup` `UserService`'s methods which resulted in not indexing the related subtrees.

Required PR: https://github.com/ezsystems/ezplatform-solr-search-engine/pull/223

`3.3.` PR: https://github.com/ezsystems/ezplatform-kernel/pull/269

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [x] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ezsystems/engineering-team`).

2021-10-27 07:34 UTC, Nattfarinn requested changes

2021-10-27 07:34 UTC, Nattfarinn commented on eZ/Publish/Core/Repository/UserService.php
>          } catch (Exception $e) {
Previously it was the `void` method. If we concern about BC and that is the reason we are not altering the method signature and interface, make adjustments to the docblock and add `@return`.

2021-10-27 07:34 UTC, Nattfarinn commented on eZ/Publish/Core/Repository/UserService.php
> +                    return $userLocation->id;
Same here.

2021-10-27 07:34 UTC, Nattfarinn commented on eZ/Publish/Core/Search/Common/Slot/AssignUserToUserGroup.php
> +namespace eZ\Publish\Core\Search\Common\Slot;
~@alongosz what about NS? Should we use new one in `2.5`?~

Nevermind. It will be deleted during merge up anyway.

2021-10-27 07:34 UTC, Nattfarinn commented on eZ/Publish/Core/SignalSlot/Signal/UserService/UnAssignUserFromUserGroupSignal.php
> +     * @var mixed
Why `mixed`?

2021-10-27 07:34 UTC, Nattfarinn commented on eZ/Publish/Core/SignalSlot/Signal/UserService/AssignUserToUserGroupSignal.php
> +     * @var mixed
Why `mixed`?

2021-10-27 07:34 UTC, Nattfarinn commented on eZ/Publish/Core/Search/Common/Slot/UnAssignUserFromUserGroup.php
> +class UnAssignUserFromUserGroup extends Slot
```suggestion
final class UnAssignUserFromUserGroup extends Slot
```

2021-10-27 07:34 UTC, Nattfarinn commented on eZ/Publish/Core/Search/Common/Slot/AssignUserToUserGroup.php
> +class AssignUserToUserGroup extends AbstractSubtree
```suggestion
final class AssignUserToUserGroup extends AbstractSubtree
```

2021-10-27 08:16 UTC, adamwojs commented on eZ/Publish/Core/Repository/UserService.php
>          } catch (Exception $e) {
Since v3.0 there is `: void` in method signature so this will be BC break.

2021-10-27 08:18 UTC, adamwojs commented
@barw4 Could you please provide PRs for ezplatform-kernel and ezplatform-elastic-search-engine?

2021-10-27 08:21 UTC, Steveb-p commented on eZ/Publish/Core/Repository/UserService.php
>          } catch (Exception $e) {
I'm not really ok with the fact that we will return **just** the ID of assigned Location. This seems short-sighted, as it will transform any future changes to value returned from this method a BC break.

Ideally, a new `User` object would be returned, as that is the domain of the service/method. Although it would also cause an additional database query.

Returning `Location` would feel incorrect - why would a method that assigns User to UserGroup return a Location?

2021-10-27 08:37 UTC, alongosz commented on eZ/Publish/Core/Search/Common/Slot/AssignUserToUserGroup.php
> +namespace eZ\Publish\Core\Search\Common\Slot;
> ~@alongosz what about NS? Should we use new one in `2.5`?~
> 
> Nevermind. It will be deleted during merge up anyway.

Ah, yes, this case is very specific. It can stay like this, though without a comment I would probably also requested the change :D

2021-10-27 13:48 UTC, barw4 commented on eZ/Publish/Core/Repository/UserService.php
>          } catch (Exception $e) {
@Steveb-p because we won't be able to reindex the `location` which has just been deleted. At the point of creating a Signal, the location is gone so we cannot load it via Slot using `persistanceHandler` to reindex. So I need its id.

What's the consensus on the return type? Switching it to `void` or something else means completely scrapping this solution. ping @adamwojs, @Nattfarinn, @alongosz

2021-11-26 13:52 UTC, alongosz commented on eZ/Publish/Core/Repository/UserService.php
>          } catch (Exception $e) {
The issue is that the solution won't be "mergable" into 3.3-related repository/branch. You need to assume there's contracted BC promise placing there `: void` and change the solution accordingly. 

Please remember that "done" applies to all supported versions, not just the lowest one. You need to have merge up strategy and given the `: void` issue Adam discovered, the solution here should be forward compatible.

2021-11-26 13:54 UTC, alongosz requested changes
As stated in https://github.com/ezsystems/ezpublish-kernel/pull/3125#discussion_r757511980 and by the other Reviewers.

2021-11-29 16:58 UTC, barw4 commented on eZ/Publish/Core/Repository/UserService.php
>          } catch (Exception $e) {
Resolved in the newest commits. Not sure why I was trying to do this using `indexLocation` when the correct use was `indexContent` 😿

2021-11-30 08:25 UTC, alongosz requested changes
It looks ok now. What I'm missing is test coverage, for the use case the integration one.

2021-12-01 09:20 UTC, alongosz requested changes
Looks complete now, CS remark (more refactoring needed to align with it):

2021-12-01 09:20 UTC, alongosz commented on eZ/Publish/API/Repository/Tests/UserServiceTest.php
> +        self::assertEquals($count + 1, $count2);
Naming:
```suggestion
        self::assertEquals($expectedCount, $actualCount);
```

2021-12-01 09:20 UTC, alongosz commented on eZ/Publish/API/Repository/Tests/UserServiceTest.php
> +        self::assertEquals($count - 1, $count2);
```suggestion
        self::assertEquals($expectedCount, $actualCount);
```

2021-12-01 09:26 UTC, alongosz approved these changes

2021-12-01 11:08 UTC, barw4 commented
Solr test most likely failing from lack of https://github.com/ezsystems/ezplatform-solr-search-engine/pull/223

2021-12-03 11:29 UTC, barw4 commented
@adamwojs @alongosz PR for `3.3` has been created: https://github.com/ezsystems/ezplatform-kernel/pull/269, Elastic PR wasn't necessary.

2021-12-04 08:55 UTC, adamwojs approved these changes

2021-12-04 10:07 UTC, Steveb-p approved these changes
Noticed that the comments requesting to add `final` to introduced classes were discarded without explanation. Why is that? `final` protects our interests first & foremost, because we can safely change the classes in question without fear of breaking.

I know that this is `7.5` version and those classes will be dropped - or rather, they will be discarded when performing merge up - but still, it's a 20 second effort at most.

Unless, of course, there was a reason that was not posted here?

2021-12-04 10:07 UTC, Steveb-p commented on eZ/Publish/API/Repository/Tests/UserServiceTest.php
> +    public function testAssignUserToGroupWithLocationsValidation()
```suggestion
    public function testAssignUserToGroupWithLocationsValidation(): void
```

2021-12-06 10:22 UTC, barw4 commented
`final` remarks were discarded as they applied to my previous solution which has been scrapped and I forgot to apply them afterwards.

2021-12-10 07:10 UTC, tomaszszopinski approved these changes
QA approved on eZPlatform 2.5.

2021-12-10 09:40 UTC, merged

2021-12-10 13:48 UTC, barw4 commented
Merged into:
`ezplatform-kernel`: https://github.com/ezsystems/ezplatform-kernel/commit/4be12335c3a7ec84097d95d5b79a4c1e812dc9d8
`ibexa/core/main` PR: https://github.com/ibexa/core/pull/36