IBX-2500: Fixed number of iterations in `normalize-paths` command
ezsystems/ezpublish-kernel pull request #3143
Opened 2022-03-08 16:37 UTC by barw4

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-2500](https://issues.ibexa.co/browse/IBX-2500)
| **Type**                                   | bug
| **Target eZ Platform version** | `v2.5`
| **BC breaks**                          | no

Previously it could occur, that when having multiple translations and versions, iterations could be finished before the command had processed all images.

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [ ] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ezsystems/engineering-team`).

2022-03-09 11:08 UTC, alongosz requested changes
`$this->imageGateway` in the command is of type `eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway`, yet you're changing `eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\DoctrineStorage` only. Something doesn't add up here. Was `countDistinctImages` not defined in the abstract Gateway?

2022-03-09 11:14 UTC, barw4 commented
> Was countDistinctImages not defined in the abstract Gateway?

@alongosz you are correct, it wasn't.

2022-03-09 11:28 UTC, alongosz commented
@barw4 then this needs to be fixed. Now it relies on a polymorphic call which should be visible in PHPStorm via static analysis.

2022-03-09 18:49 UTC, barw4 commented
@alongosz resolved in https://github.com/ezsystems/ezpublish-kernel/pull/3143/commits/0bb51dff00946cad30cf4dcbf4b7bce585437f05

2022-03-10 15:23 UTC, mateuszbieniek approved these changes

2022-03-10 15:23 UTC, mateuszbieniek commented
Looks good to me

2022-03-13 23:32 UTC, alongosz approved these changes

2022-03-13 23:33 UTC, alongosz commented
@mateuszbieniek once it gets 2nd maintainer approve it can go to QA.

2022-03-14 08:47 UTC, webhdx approved these changes

2022-03-14 09:06 UTC, Steveb-p approved these changes

2022-03-14 09:35 UTC, damianz5 approved these changes

2022-03-18 14:54 UTC, micszo approved these changes
QA Approved on eZ Platform EE v2.5.27 with diff.

2022-03-18 15:13 UTC, merged

2022-03-18 15:57 UTC, barw4 commented
Merged into:
`ezsystems/ezplatform-kernel/1.3`: https://github.com/ezsystems/ezplatform-kernel/commit/ca232009d90f0a4fa723452e303b3aa7812c1926
`ibexa/core/main`: https://github.com/ibexa/core/pull/95